### ISSUE TITLE
TypeError: SyncBailHook is not a constructor

### ISSUE THREAD

**Issue by entranced** [module-federation/webpack-4#8]
I get this error while trying to use the plugin:

```
C:\src\app\node_modules\mf-webpack4\lib\plugin.js:46
      runtimeFetchContainer: new SyncBailHook(["remote", 'url'])
                             ^

TypeError: SyncBailHook is not a constructor
    at new ModuleFederationPlugin (C:\src\app\node_modules\mf-webpack4\lib\plugin.js:46:30)
    at Object.<anonymous> (C:\src\app\build\webpack.base.conf.js:69:9)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\src\app\build\webpack.dev.conf.js:7:27)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
```

Looks like the tapable dependency is used, but not declared anywhere in the package.json. If I install tapable it works fine, but I want to confirm the expected version to be used here.

**Comment by zhangHongEn** [comment]
It turns out that there are multiple tapables, mf-webpack4 may have introduced tapable@0.1.10, it seems that I really need to set it as dependencies

**Comment by zhangHongEn** [comment]
I haven't tried the version above 2, and it may be possible

**Comment by zhangHongEn** [comment]
You can install "tapable": "^1.1.3" first, and I will add it to dependencies at night

**Comment by zhangHongEn** [comment]
🤝, mf-webpack4@1.4.1 released
